//------------------------------------------------------------------------------
// TI Confidential - NDA Restrictions
//
// Copyright (c) 2011 Texas Instruments, Inc.
//
//    This is an unpublished work created in the year stated above.
//    Texas Instruments owns all rights in and to this work and
//    intends to maintain and protect it as an unpublished copyright.
//    In the event of either inadvertent or deliberate publication,
//    the above stated date shall be treated as the year of first
//    publication. In the event of such publication, Texas Instruments
//    intends to enforce its rights in the work under the copyright
//    laws as a published work.
//
//------------------------------------------------------------------------------
///
/// \file            data_entry.h
/// \brief           Definitions of API for data exchange
///
///                  This file is generated by create_command.pl
///
/// \author          Low Power RF Wireless Business Unit
///                  Helge Coward (h.coward@ti.com)
///
/// \date            Thu Nov 17 10:26:10 CET 2011
///
//------------------------------------------------------------------------------

#ifndef __DATA_ENTRY_H
#define __DATA_ENTRY_H

#include <stdint.h>
#include "mailbox.h"

typedef struct {
   uint8_t* pNextEntry;
   uint8_t status;
   struct {
      uint8_t type:2;
      uint8_t lenSz:2;
      uint8_t irqIntv:4;
   } config;
   uint16_t length;
   uint8_t data;
   uint8_t __dummy0;
   uint16_t nextIndex;
   uint8_t rxData;
} rfc_dataEntry_t;

#endif
