//*****************************************************************************
// This file is AUTOGENERATED! Do not check in or edit.
// Generated on Mon Oct 14 15:32:39 2013
//*****************************************************************************
#ifndef __DBGID_H
#define __DBGID_H
#ifndef _DBGID_H
#warning "_dbgid_sys_mst.h should not be directly included in a C file. Include dbgid_sys_mst.h instead."
#endif

#include "dbg.h"

DBG_DEF(DBGID_cmd_radio_c_1553, 8, DBGCH3, -1, "Frac orig read Q=0x%08X", "C:/svn_work/srf04/cc26xx_branches/test_fw_add_cc13xx_pg1_support/fw/IAR/../src/cmd_radio.c", 1553)
DBG_DEF(DBGID_cmd_radio_c_1560, 6, DBGCH3, -1, "Frac override read Q=0x%08X!!", "C:/svn_work/srf04/cc26xx_branches/test_fw_add_cc13xx_pg1_support/fw/IAR/../src/cmd_radio.c", 1560)
DBG_DEF(DBGID_synthcal_lib_c_462, 14, DBGCH3, 0, "Doing WriteXtalRegInfo. Using 24 MHz XTAL", "C:/svn_work/srf04/cc26xx_branches/test_fw_add_cc13xx_pg1_support/fw/IAR/../src/modules/radiolowlevel/synthcal_lib.c", 462)
DBG_DEF(DBGID_synthcal_lib_c_517, 21, DBGCH3, 0, "Synth is configured in TX mode", "C:/svn_work/srf04/cc26xx_branches/test_fw_add_cc13xx_pg1_support/fw/IAR/../src/modules/radiolowlevel/synthcal_lib.c", 517)
DBG_DEF(DBGID_synthcal_lib_c_520, 15, DBGCH3, 0, "Synth is configured in RX mode", "C:/svn_work/srf04/cc26xx_branches/test_fw_add_cc13xx_pg1_support/fw/IAR/../src/modules/radiolowlevel/synthcal_lib.c", 520)
DBG_DEF(DBGID_synthcal_lib_c_552, 5, DBGCH3, 0, "Tune phase changing from 1 to 3 -- DIG is Enabled", "C:/svn_work/srf04/cc26xx_branches/test_fw_add_cc13xx_pg1_support/fw/IAR/../src/modules/radiolowlevel/synthcal_lib.c", 552)
DBG_DEF(DBGID_synthcal_lib_c_568, 4, DBGCH3, 1, "Reading SYNTHSTATUS3 = %d", "C:/svn_work/srf04/cc26xx_branches/test_fw_add_cc13xx_pg1_support/fw/IAR/../src/modules/radiolowlevel/synthcal_lib.c", 568)
DBG_DEF(DBGID_synthcal_lib_c_593, 10, DBGCH3, 1, "Tune phase changing from 3 to 7 -- 1/KT is loaded %d", "C:/svn_work/srf04/cc26xx_branches/test_fw_add_cc13xx_pg1_support/fw/IAR/../src/modules/radiolowlevel/synthcal_lib.c", 593)
DBG_DEF(DBGID_synthcal_lib_c_651, 3, DBGCH3, 1, "Tune phase changing from 7 to 15. dco_span is %d", "C:/svn_work/srf04/cc26xx_branches/test_fw_add_cc13xx_pg1_support/fw/IAR/../src/modules/radiolowlevel/synthcal_lib.c", 651)
DBG_DEF(DBGID_synthcal_lib_c_652, 17, DBGCH3, 1, "ikt is %d", "C:/svn_work/srf04/cc26xx_branches/test_fw_add_cc13xx_pg1_support/fw/IAR/../src/modules/radiolowlevel/synthcal_lib.c", 652)
DBG_DEF(DBGID_synthcal_lib_c_653, 16, DBGCH3, 1, "Calculated alpha is %d", "C:/svn_work/srf04/cc26xx_branches/test_fw_add_cc13xx_pg1_support/fw/IAR/../src/modules/radiolowlevel/synthcal_lib.c", 653)
DBG_DEF(DBGID_synthcal_lib_c_654, 7, DBGCH3, 1, "Calculated beta is %d", "C:/svn_work/srf04/cc26xx_branches/test_fw_add_cc13xx_pg1_support/fw/IAR/../src/modules/radiolowlevel/synthcal_lib.c", 654)
DBG_DEF(DBGID_synthcal_lib_c_667, 19, DBGCH3, 0, "PLL is LOCKED!!!", "C:/svn_work/srf04/cc26xx_branches/test_fw_add_cc13xx_pg1_support/fw/IAR/../src/modules/radiolowlevel/synthcal_lib.c", 667)

#endif //__DBGID_H
