//*****************************************************************************
// This file is AUTOGENERATED! Do not check in or edit.
// Generated on Fri Sep 20 08:46:41 2013
//*****************************************************************************
#ifndef __DBGID_H
#define __DBGID_H
#ifndef _DBGID_H
#warning "_dbgid_sys_slv.h should not be directly included in a C file. Include dbgid_sys_slv.h instead."
#endif

#include "dbg.h"

DBG_DEF(DBGID_digval_c_194, 10, DBGCH3, 1, "RSSI   = %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/digval.c", 194)
DBG_DEF(DBGID_digval_c_195, 28, DBGCH3, 1, "RFGain = %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/digval.c", 195)
DBG_DEF(DBGID_digval_c_203, 7, DBGCH3, 1, "+++ Packet RX: %2d errors", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/digval.c", 203)
DBG_DEF(DBGID_digval_c_207, 34, DBGCH3, 1, "+++++ Byte Errored in %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/digval.c", 207)
DBG_DEF(DBGID_digval_c_208, 29, DBGCH3, 2, "   rxPayload : %2x    rxExpected : %2x", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/digval.c", 208)
DBG_DEF(DBGID_digval_c_238, 21, DBGCH3, 2, "Configure Modem in Infinite TX (MCEPATCH %d RFEPATCH %d)", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/digval.c", 238)
DBG_DEF(DBGID_digval_c_252, 33, DBGCH3, 2, "Configure Modem in Infinite RX (MCEPATCH %d RFEPATCH %d)", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/digval.c", 252)
DBG_DEF(DBGID_digval_c_293, 9, DBGCH3, 0, "Capture is started", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/digval.c", 293)
DBG_DEF(DBGID_digval_c_296, 18, DBGCH3, 0, "Capture is completed", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/digval.c", 296)
DBG_DEF(DBGID_digval_c_327, 23, DBGCH3, 3, "Gain setting %d DC I channel=%d DC Q channel=%d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/digval.c", 327)
DBG_DEF(DBGID_digval_c_91, 36, DBGCH3, 1, "SynthCalibrationTX() in Mode %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/digval.c", 91)
DBG_DEF(DBGID_low_level_radio_libs_c_426, 27, DBGCH3, -2, "I=%d Q=%d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 426)
DBG_DEF(DBGID_low_level_radio_libs_c_434, 16, DBGCH3, -1, "Average of I samples %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 434)
DBG_DEF(DBGID_low_level_radio_libs_c_435, 25, DBGCH3, -1, "Average of Q samples %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 435)
DBG_DEF(DBGID_low_level_radio_libs_c_456, 17, DBGCH3, -1, "Average power of I samples %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 456)
DBG_DEF(DBGID_low_level_radio_libs_c_457, 6, DBGCH3, -1, "Average power of Q samples %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 457)
DBG_DEF(DBGID_low_level_radio_libs_c_463, 19, DBGCH3, -1, "Average amplitude of I samples %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 463)
DBG_DEF(DBGID_low_level_radio_libs_c_464, 8, DBGCH3, -1, "Average amplitude of Q samples %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 464)
DBG_DEF(DBGID_low_level_radio_libs_c_473, 32, DBGCH3, -1, "Amplitude ratio is %d / 128", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 473)
DBG_DEF(DBGID_low_level_radio_libs_c_491, 24, DBGCH3, -1, "Mean of IQ product is %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 491)
DBG_DEF(DBGID_low_level_radio_libs_c_496, 38, DBGCH3, -1, "Phase error is %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 496)
DBG_DEF(DBGID_low_level_radio_libs_c_688, 37, DBGCH3, 1, "Run from MCE ram is set to : %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 688)
DBG_DEF(DBGID_low_level_radio_libs_c_689, 39, DBGCH3, 1, "Run from RFE ram is set to : %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 689)
DBG_DEF(DBGID_low_level_radio_libs_c_838, 5, DBGCH3, 0, "Finished SendCW (WARNING: assume RFE patch!)", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 838)
DBG_DEF(DBGID_low_level_radio_libs_c_936, 11, DBGCH3, 2, "Start Capture SRC = %d   ID = %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 936)
DBG_DEF(DBGID_low_level_radio_libs_c_937, 30, DBGCH3, 2, "Start Capture START = %d STOP = %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 937)
DBG_DEF(DBGID_low_level_radio_libs_c_953, 31, DBGCH3, 0, "Timeout from RX", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/low_level_radio_libs.c", 953)
DBG_DEF(DBGID_main_c_181, 14, DBGCH3, 0, "Hello world!", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/main.c", 181)
DBG_DEF(DBGID_synthcal_lib_c_462, 12, DBGCH3, 0, "Doing WriteXtalRegInfo. Using 24 MHz XTAL", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/synthcal_lib.c", 462)
DBG_DEF(DBGID_synthcal_lib_c_517, 41, DBGCH3, 0, "Synth is configured in TX mode", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/synthcal_lib.c", 517)
DBG_DEF(DBGID_synthcal_lib_c_520, 13, DBGCH3, 0, "Synth is configured in RX mode", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/synthcal_lib.c", 520)
DBG_DEF(DBGID_synthcal_lib_c_552, 4, DBGCH3, 0, "Tune phase changing from 1 to 3 -- DIG is Enabled", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/synthcal_lib.c", 552)
DBG_DEF(DBGID_synthcal_lib_c_568, 3, DBGCH3, 1, "Reading SYNTHSTATUS3 = %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/synthcal_lib.c", 568)
DBG_DEF(DBGID_synthcal_lib_c_593, 26, DBGCH3, 1, "Tune phase changing from 3 to 7 -- 1/KT is loaded %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/synthcal_lib.c", 593)
DBG_DEF(DBGID_synthcal_lib_c_651, 20, DBGCH3, 1, "Tune phase changing from 7 to 15. dco_span is %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/synthcal_lib.c", 651)
DBG_DEF(DBGID_synthcal_lib_c_652, 15, DBGCH3, 1, "ikt is %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/synthcal_lib.c", 652)
DBG_DEF(DBGID_synthcal_lib_c_653, 35, DBGCH3, 1, "Calculated alpha is %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/synthcal_lib.c", 653)
DBG_DEF(DBGID_synthcal_lib_c_654, 22, DBGCH3, 1, "Calculated beta is %d", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/synthcal_lib.c", 654)
DBG_DEF(DBGID_synthcal_lib_c_667, 40, DBGCH3, 0, "PLL is LOCKED!!!", "C:/Users/x0203106/Documents/Projects/thesis/code/digval/cc26xx/fw/RadioLowLevel/src/synthcal_lib.c", 667)

#endif //__DBGID_H
