//*****************************************************************************
// This file is AUTOGENERATED! Do not check in or edit.
// Generated on Mon Oct 14 15:32:39 2013
//*****************************************************************************
#ifndef _DBGID_H
#define _DBGID_H

#define _NO_ASSERT
#include "dbg.h"
#ifndef _MAKEDEPEND
#include "_dbgid_sys_mst.h"
#endif

#endif //_DBGID_H
