//------------------------------------------------------------------------------
// TI Confidential - NDA Restrictions
//
// Copyright (c) 2011 Texas Instruments, Inc.
//
//    This is an unpublished work created in the year stated above.
//    Texas Instruments owns all rights in and to this work and
//    intends to maintain and protect it as an unpublished copyright.
//    In the event of either inadvertent or deliberate publication,
//    the above stated date shall be treated as the year of first
//    publication. In the event of such publication, Texas Instruments
//    intends to enforce its rights in the work under the copyright
//    laws as a published work.
//
//------------------------------------------------------------------------------
///
/// \file            radio_par.h
/// \brief           Definition of radio parameter override registers
///
///                  This file is generated by create_command.pl
///
/// \author          Low Power RF Wireless Business Unit
///                  Helge Coward (h.coward@ti.com)
///
/// \date            Thu Nov 17 10:26:10 CET 2011
///
//------------------------------------------------------------------------------

#ifndef __RADIO_PAR_H
#define __RADIO_PAR_H

#include <stdint.h>

/// Type for the radio configuration defined in radio_par_def.txt
//
/// When accessed, a typecast is made to the structs defined below. The definition here is uint32_t 
/// to ensure the  correct alignment. It must be checked that the array is large enough for the structs.
///
typedef uint32_t radioCfg_t[48];

extern radioCfg_t radioCfg;

#define _POSITION_radioPar_maxFutureTime                        0
#define _TYPE_radioPar_maxFutureTime                            uint16_t
#define _POSITION_radioPar_numSwBits                            2
#define _TYPE_radioPar_numSwBits                                uint8_t
#define _POSITION_radioPar_preamCtrl                            3
#define _TYPE_radioPar_preamCtrl                                uint8_t
#define _POSITION_radioPar_preamPattern                         4
#define _TYPE_radioPar_preamPattern                             uint16_t
#define _POSITION_radioPar_bNoPtrCheck                          6
#define _TYPE_radioPar_bNoPtrCheck                              uint8_t
#define _POSITION_radioPar_rssiOverride                         7
#define _TYPE_radioPar_rssiOverride                             int8_t
#define _POSITION_radioPar_modIsfCfgVal                         8
#define _TYPE_radioPar_modIsfCfgVal                             uint32_t
#define _POSITION_radioPar_pModIsfShape                         12
#define _TYPE_radioPar_pModIsfShape                             uint32_t const *
#define _POSITION_radioPar_crcWhConfig                          16
#define _TYPE_radioPar_crcWhConfig                              uint8_t
#define _BITPOS_radioPar_crcWhConfig_bWhEn                      0
#define _NBITS_radioPar_crcWhConfig_bWhEn                       1
#define _BITPOS_radioPar_crcWhConfig_bWhBitRev                  1
#define _NBITS_radioPar_crcWhConfig_bWhBitRev                   1
#define _BITPOS_radioPar_crcWhConfig_bMsbFirst                  2
#define _NBITS_radioPar_crcWhConfig_bMsbFirst                   1
#define _BITPOS_radioPar_crcWhConfig_bNoSwPreamProg             3
#define _NBITS_radioPar_crcWhConfig_bNoSwPreamProg              1
#define _BITPOS_radioPar_crcWhConfig_bSwDepPream                4
#define _NBITS_radioPar_crcWhConfig_bSwDepPream                 1
#define _POSITION_radioPar_numCrcBits                           17
#define _TYPE_radioPar_numCrcBits                               uint8_t
#define _POSITION_radioPar_introduceCrcErr                      18
#define _TYPE_radioPar_introduceCrcErr                          uint16_t
#define _POSITION_radioPar_crcInit                              20
#define _TYPE_radioPar_crcInit                                  uint32_t
#define _POSITION_radioPar_crcXor                               24
#define _TYPE_radioPar_crcXor                                   uint32_t
#define _POSITION_radioPar_whInit                               28
#define _TYPE_radioPar_whInit                                   uint32_t
#define _POSITION_radioPar_startToTxRatOffset                   32
#define _TYPE_radioPar_startToTxRatOffset                       uint16_t
#define _POSITION_radioPar_startToRxRatOffset                   34
#define _TYPE_radioPar_startToRxRatOffset                       uint16_t
#define _POSITION_radioPar_startToSynthRatOffset                36
#define _TYPE_radioPar_startToSynthRatOffset                    uint16_t
#define _POSITION_radioPar_txToRxRatOffset                      38
#define _TYPE_radioPar_txToRxRatOffset                          uint16_t
#define _POSITION_radioPar_rxToTxRatOffset                      40
#define _TYPE_radioPar_rxToTxRatOffset                          uint16_t
#define _POSITION_radioPar_syncTimeAdjust                       42
#define _TYPE_radioPar_syncTimeAdjust                           uint16_t
#define _POSITION_radioPar_rxFifoThrSleep                       44
#define _TYPE_radioPar_rxFifoThrSleep                           uint8_t
#define _POSITION_radioPar_txFifoThrSleep                       45
#define _TYPE_radioPar_txFifoThrSleep                           uint8_t
#define _POSITION_radioPar_ratTicksPerBit                       46
#define _TYPE_radioPar_ratTicksPerBit                           uint16_t
#define _POSITION_radioPar_mdmFreqWordOvr                       48
#define _TYPE_radioPar_mdmFreqWordOvr                           uint16_t
#define _BITPOS_radioPar_mdmFreqWordOvr_freqWordOvr             0
#define _NBITS_radioPar_mdmFreqWordOvr_freqWordOvr              12
#define _BITPOS_radioPar_mdmFreqWordOvr_bOvrMdmRfCh             14
#define _NBITS_radioPar_mdmFreqWordOvr_bOvrMdmRfCh              1
#define _BITPOS_radioPar_mdmFreqWordOvr_bWrMdmRfCh              15
#define _NBITS_radioPar_mdmFreqWordOvr_bWrMdmRfCh               1
#define _POSITION_radioPar_mdmRxIntFreq                         50
#define _TYPE_radioPar_mdmRxIntFreq                             int16_t
#define _POSITION_radioPar_mdmTxIntFreq                         52
#define _TYPE_radioPar_mdmTxIntFreq                             int16_t
#define _POSITION_radioPar_mdmPShift                            54
#define _TYPE_radioPar_mdmPShift                                uint8_t
#define _POSITION_radioPar_mdmQShift                            55
#define _TYPE_radioPar_mdmQShift                                uint8_t
#define _LAST_POSITION_radioPar                                 55
#define _LAST_TYPE_radioPar                                     uint8_t

#define _N_INIT_SETS_radioPar 3
#define _N_INIT_WORDS_radioPar 14
#define _START_INIT_WIDX_radioPar 0
static uint32_t const __init_radioPar[_N_INIT_SETS_radioPar][_N_INIT_WORDS_radioPar] = {
   {
      0x0720C000, 0x8000AAAA, 0x00036029, 0x000000C0, 0x00001811, 0x55555500, 0x00000000, 0xA6000000, 
      0x01000180, 0x013A0320, 0x011B0258, 0x00401830, 0x10000000, 0x06041000
   },
   {
      0x0020C000, 0x80000000, 0x000360E1, 0x00000000, 0x00001008, 0x00000000, 0x00000000, 0x00000000, 
      0x01000180, 0x013A0320, 0x02DD0300, 0x01001030, 0x10000000, 0x06051000
   },
   {
      0x0720C000, 0x8000AAAA, 0x00036035, 0x000000D8, 0x00001014, 0xFFFF0000, 0x00000000, 0xF0000000, 
      0x01000180, 0x013A0320, 0x008B0243, 0x00201830, 0x10000000, 0x06051000
   }
};

#define _POSITION_synthPar_preDivValues                         64
#define _TYPE_synthPar_preDivValues                             uint32_t
#define _BITPOS_synthPar_preDivValues_F_Xtal_F_FrefFast         0
#define _NBITS_synthPar_preDivValues_F_Xtal_F_FrefFast          6
#define _BITPOS_synthPar_preDivValues_F_Xtal_F_MidSar           6
#define _NBITS_synthPar_preDivValues_F_Xtal_F_MidSar            9
#define _BITPOS_synthPar_preDivValues_F_Xtal_F_FineCalib        15
#define _NBITS_synthPar_preDivValues_F_Xtal_F_FineCalib         11
#define _BITPOS_synthPar_preDivValues_F_Xtal_PllFref            26
#define _NBITS_synthPar_preDivValues_F_Xtal_PllFref             6
#define _POSITION_synthPar_K1                                   68
#define _TYPE_synthPar_K1                                       uint32_t
#define _POSITION_synthPar_K2BL                                 72
#define _TYPE_synthPar_K2BL                                     uint32_t
#define _POSITION_synthPar_K2AL                                 76
#define _TYPE_synthPar_K2AL                                     uint32_t
#define _POSITION_synthPar_K3BL                                 80
#define _TYPE_synthPar_K3BL                                     uint32_t
#define _POSITION_synthPar_K3AL                                 84
#define _TYPE_synthPar_K3AL                                     uint32_t
#define _POSITION_synthPar_K5                                   88
#define _TYPE_synthPar_K5                                       uint32_t
#define _POSITION_synthPar_MK                                   92
#define _TYPE_synthPar_MK                                       uint16_t
#define _POSITION_synthPar_M2K                                  94
#define _TYPE_synthPar_M2K                                      uint8_t
#define _POSITION_synthPar_M3K                                  95
#define _TYPE_synthPar_M3K                                      uint8_t
#define _POSITION_synthPar_M4K                                  96
#define _TYPE_synthPar_M4K                                      uint8_t
#define _POSITION_synthPar_fineBotCode                          97
#define _TYPE_synthPar_fineBotCode                              uint8_t
#define _POSITION_synthPar_fineTopCode                          98
#define _TYPE_synthPar_fineTopCode                              uint8_t
#define _POSITION_synthPar_loopCoeffMsbVal                      99
#define _TYPE_synthPar_loopCoeffMsbVal                          uint8_t
#define _POSITION_synthPar_edgeSelTdcTh                         100
#define _TYPE_synthPar_edgeSelTdcTh                             uint16_t
#define _POSITION_synthPar_pllControl2LshwVal                   102
#define _TYPE_synthPar_pllControl2LshwVal                       uint16_t
#define _POSITION_synthPar_synthRegAnaDivVal                    104
#define _TYPE_synthPar_synthRegAnaDivVal                        uint32_t
#define _POSITION_synthPar_midSarInitVal                        108
#define _TYPE_synthPar_midSarInitVal                            uint8_t
#define _POSITION_synthPar_synthRegPllMValueMsb                 109
#define _TYPE_synthPar_synthRegPllMValueMsb                     uint8_t
#define _POSITION_synthPar_config                               110
#define _TYPE_synthPar_config                                   uint16_t
#define _BITPOS_synthPar_config_b24MHzXtal                      0
#define _NBITS_synthPar_config_b24MHzXtal                       1
#define _BITPOS_synthPar_config_bSkipTdcCalib                   1
#define _NBITS_synthPar_config_bSkipTdcCalib                    1
#define _BITPOS_synthPar_config_bSkipCoarseCalib                2
#define _NBITS_synthPar_config_bSkipCoarseCalib                 1
#define _BITPOS_synthPar_config_bSkipMidCalib                   3
#define _NBITS_synthPar_config_bSkipMidCalib                    1
#define _BITPOS_synthPar_config_bForceTxMode                    4
#define _NBITS_synthPar_config_bForceTxMode                     1
#define _BITPOS_synthPar_config_bOpenLoop1Pt                    5
#define _NBITS_synthPar_config_bOpenLoop1Pt                     1
#define _BITPOS_synthPar_config_bDisableSynthProg               7
#define _NBITS_synthPar_config_bDisableSynthProg                1
#define _BITPOS_synthPar_config_bDisableSynthEnaPoll            8
#define _NBITS_synthPar_config_bDisableSynthEnaPoll             1
#define _POSITION_synthPar_coarsePrecal                         112
#define _TYPE_synthPar_coarsePrecal                             uint8_t
#define _POSITION_synthPar_coarsePrecal0                        112
#define _TYPE_synthPar_coarsePrecal0                            uint8_t
#define _POSITION_synthPar_coarsePrecal1                        113
#define _TYPE_synthPar_coarsePrecal1                            uint8_t
#define _POSITION_synthPar_coarsePrecal2                        114
#define _TYPE_synthPar_coarsePrecal2                            uint8_t
#define _POSITION_synthPar_coarsePrecal3                        115
#define _TYPE_synthPar_coarsePrecal3                            uint8_t
#define _POSITION_synthPar_midPrecal                            116
#define _TYPE_synthPar_midPrecal                                uint8_t
#define _POSITION_synthPar_midPrecal00                          116
#define _TYPE_synthPar_midPrecal00                              uint8_t
#define _POSITION_synthPar_midPrecal01                          117
#define _TYPE_synthPar_midPrecal01                              uint8_t
#define _POSITION_synthPar_midPrecal02                          118
#define _TYPE_synthPar_midPrecal02                              uint8_t
#define _POSITION_synthPar_midPrecal03                          119
#define _TYPE_synthPar_midPrecal03                              uint8_t
#define _POSITION_synthPar_midPrecal04                          120
#define _TYPE_synthPar_midPrecal04                              uint8_t
#define _POSITION_synthPar_midPrecal05                          121
#define _TYPE_synthPar_midPrecal05                              uint8_t
#define _POSITION_synthPar_midPrecal06                          122
#define _TYPE_synthPar_midPrecal06                              uint8_t
#define _POSITION_synthPar_midPrecal07                          123
#define _TYPE_synthPar_midPrecal07                              uint8_t
#define _POSITION_synthPar_midPrecal08                          124
#define _TYPE_synthPar_midPrecal08                              uint8_t
#define _POSITION_synthPar_midPrecal09                          125
#define _TYPE_synthPar_midPrecal09                              uint8_t
#define _POSITION_synthPar_midPrecal10                          126
#define _TYPE_synthPar_midPrecal10                              uint8_t
#define _POSITION_synthPar_midPrecal11                          127
#define _TYPE_synthPar_midPrecal11                              uint8_t
#define _POSITION_synthPar_midPrecal12                          128
#define _TYPE_synthPar_midPrecal12                              uint8_t
#define _POSITION_synthPar_midPrecal13                          129
#define _TYPE_synthPar_midPrecal13                              uint8_t
#define _POSITION_synthPar_midPrecal14                          130
#define _TYPE_synthPar_midPrecal14                              uint8_t
#define _POSITION_synthPar_midPrecal15                          131
#define _TYPE_synthPar_midPrecal15                              uint8_t
#define _POSITION_synthPar_tdcPrecal                            132
#define _TYPE_synthPar_tdcPrecal                                uint8_t
#define _POSITION_synthPar_tdcPrecal0                           132
#define _TYPE_synthPar_tdcPrecal0                               uint16_t
#define _POSITION_synthPar_tdcPrecal1                           134
#define _TYPE_synthPar_tdcPrecal1                               uint16_t
#define _LAST_POSITION_synthPar                                 134
#define _LAST_TYPE_synthPar                                     uint16_t

#define _N_INIT_SETS_synthPar 1
#define _N_INIT_WORDS_synthPar 18
#define _START_INIT_WIDX_synthPar 16
static uint32_t const __init_synthPar[_N_INIT_SETS_synthPar][_N_INIT_WORDS_synthPar] = {
   {
      0x24301E18, 0x001D5C31, 0x0001454B, 0x0000340C, 0x000E618E, 0x0005C09F, 0x00003D09, 0x01050300, 
      0x00F01004, 0x01303010, 0x00012000, 0x00010020, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 
      0x00000000, 0x00000000
   }
};

#define _POSITION_bleRadioPar_advSyncWord                       144
#define _TYPE_bleRadioPar_advSyncWord                           uint32_t
#define _POSITION_bleRadioPar_maxCrcErr                         148
#define _TYPE_bleRadioPar_maxCrcErr                             uint8_t
#define _POSITION_bleRadioPar_numDfBytes                        149
#define _TYPE_bleRadioPar_numDfBytes                            uint8_t
#define _POSITION_bleRadioPar_dataHeaderAnd                     150
#define _TYPE_bleRadioPar_dataHeaderAnd                         uint8_t
#define _POSITION_bleRadioPar_dataAutoEmptyHdr                  151
#define _TYPE_bleRadioPar_dataAutoEmptyHdr                      uint8_t
#define _POSITION_bleRadioPar_advIndHdr                         152
#define _TYPE_bleRadioPar_advIndHdr                             uint8_t
#define _POSITION_bleRadioPar_advDirIndHdr                      153
#define _TYPE_bleRadioPar_advDirIndHdr                          uint8_t
#define _POSITION_bleRadioPar_advNcIndHdr                       154
#define _TYPE_bleRadioPar_advNcIndHdr                           uint8_t
#define _POSITION_bleRadioPar_advScanIndHdr                     155
#define _TYPE_bleRadioPar_advScanIndHdr                         uint8_t
#define _POSITION_bleRadioPar_scanReqHdr                        156
#define _TYPE_bleRadioPar_scanReqHdr                            uint8_t
#define _POSITION_bleRadioPar_connectReqHdr                     157
#define _TYPE_bleRadioPar_connectReqHdr                         uint8_t
#define _POSITION_bleRadioPar_scanRspHdr                        158
#define _TYPE_bleRadioPar_scanRspHdr                            uint8_t
#define _POSITION_bleRadioPar_dataLengthOr                      160
#define _TYPE_bleRadioPar_dataLengthOr                          uint8_t
#define _POSITION_bleRadioPar_advLengthOr                       161
#define _TYPE_bleRadioPar_advLengthOr                           uint8_t
#define _POSITION_bleRadioPar_dataLenMask                       162
#define _TYPE_bleRadioPar_dataLenMask                           uint8_t
#define _POSITION_bleRadioPar_maxDataLen                        163
#define _TYPE_bleRadioPar_maxDataLen                            uint8_t
#define _POSITION_bleRadioPar_advLenMask                        164
#define _TYPE_bleRadioPar_advLenMask                            uint8_t
#define _POSITION_bleRadioPar_maxAdvLen                         165
#define _TYPE_bleRadioPar_maxAdvLen                             uint8_t
#define _POSITION_bleRadioPar_rxIfsTimeout                      166
#define _TYPE_bleRadioPar_rxIfsTimeout                          uint16_t
#define _POSITION_bleRadioPar_minLogUpperLimit                  168
#define _TYPE_bleRadioPar_minLogUpperLimit                      uint8_t
#define _POSITION_bleRadioPar_maxLogUpperLimit                  169
#define _TYPE_bleRadioPar_maxLogUpperLimit                      uint8_t
#define _POSITION_bleRadioPar_winOffsetMargin                   170
#define _TYPE_bleRadioPar_winOffsetMargin                       uint16_t
#define _POSITION_bleRadioPar_extraWinSzLimit                   172
#define _TYPE_bleRadioPar_extraWinSzLimit                       uint16_t
#define _POSITION_bleRadioPar_minWinSz                          174
#define _TYPE_bleRadioPar_minWinSz                              uint8_t
#define _POSITION_bleRadioPar_bWinOffsetNotZero                 175
#define _TYPE_bleRadioPar_bWinOffsetNotZero                     uint8_t
#define _POSITION_bleRadioPar_ticksPerConnIntStep               176
#define _TYPE_bleRadioPar_ticksPerConnIntStep                   uint16_t
#define _LAST_POSITION_bleRadioPar                              176
#define _LAST_TYPE_bleRadioPar                                  uint16_t

#define _N_INIT_SETS_bleRadioPar 1
#define _N_INIT_WORDS_bleRadioPar 9
#define _START_INIT_WIDX_bleRadioPar 36
static uint32_t const __init_bleRadioPar[_N_INIT_SETS_bleRadioPar][_N_INIT_WORDS_bleRadioPar] = {
   {
      0x8E89BED6, 0x01FF0002, 0x06020100, 0x00040503, 0x1F1F0000, 0x0288253F, 0x19880800, 0x01010600, 
      0x00001388
   }
};

#define _POSITION_ieeeRadioPar_numPreambleNibbles               144
#define _TYPE_ieeeRadioPar_numPreambleNibbles                   uint8_t
#define _POSITION_ieeeRadioPar_phyLenMask                       145
#define _TYPE_ieeeRadioPar_phyLenMask                           uint8_t
#define _POSITION_ieeeRadioPar_preambleWord                     146
#define _TYPE_ieeeRadioPar_preambleWord                         uint16_t
#define _POSITION_ieeeRadioPar_ackMacHdr                        148
#define _TYPE_ieeeRadioPar_ackMacHdr                            uint16_t
#define _POSITION_ieeeRadioPar_frameCtrlAnd                     150
#define _TYPE_ieeeRadioPar_frameCtrlAnd                         uint16_t
#define _POSITION_ieeeRadioPar_frameCtrlAndBeacon               150
#define _TYPE_ieeeRadioPar_frameCtrlAndBeacon                   uint16_t
#define _POSITION_ieeeRadioPar_frameCtrlAndData                 152
#define _TYPE_ieeeRadioPar_frameCtrlAndData                     uint16_t
#define _POSITION_ieeeRadioPar_frameCtrlAndAck                  154
#define _TYPE_ieeeRadioPar_frameCtrlAndAck                      uint16_t
#define _POSITION_ieeeRadioPar_frameCtrlAndMacCmd               156
#define _TYPE_ieeeRadioPar_frameCtrlAndMacCmd                   uint16_t
#define _POSITION_ieeeRadioPar_frameCtrlAndFt4                  158
#define _TYPE_ieeeRadioPar_frameCtrlAndFt4                      uint16_t
#define _POSITION_ieeeRadioPar_frameCtrlAndFt5                  160
#define _TYPE_ieeeRadioPar_frameCtrlAndFt5                      uint16_t
#define _POSITION_ieeeRadioPar_frameCtrlAndFt6                  162
#define _TYPE_ieeeRadioPar_frameCtrlAndFt6                      uint16_t
#define _POSITION_ieeeRadioPar_frameCtrlAndFt7                  164
#define _TYPE_ieeeRadioPar_frameCtrlAndFt7                      uint16_t
#define _POSITION_ieeeRadioPar_rxFrameEndOffset                 166
#define _TYPE_ieeeRadioPar_rxFrameEndOffset                     int16_t
#define _POSITION_ieeeRadioPar_txFrameEndOffset                 168
#define _TYPE_ieeeRadioPar_txFrameEndOffset                     int16_t
#define _POSITION_ieeeRadioPar_backoffPeriod                    170
#define _TYPE_ieeeRadioPar_backoffPeriod                        uint16_t
#define _POSITION_ieeeRadioPar_csmaSlottedWaitBeforeCca         172
#define _TYPE_ieeeRadioPar_csmaSlottedWaitBeforeCca             uint16_t
#define _POSITION_ieeeRadioPar_csmaUnslottedWaitBeforeCca       174
#define _TYPE_ieeeRadioPar_csmaUnslottedWaitBeforeCca           uint16_t
#define _POSITION_ieeeRadioPar_csmaUnslottedWaitAfterCca        176
#define _TYPE_ieeeRadioPar_csmaUnslottedWaitAfterCca            uint16_t
#define _POSITION_ieeeRadioPar_csmaUnslottedWait0Cca            178
#define _TYPE_ieeeRadioPar_csmaUnslottedWait0Cca                uint16_t
#define _POSITION_ieeeRadioPar_csmaRxWakeupTime                 180
#define _TYPE_ieeeRadioPar_csmaRxWakeupTime                     uint16_t
#define _POSITION_ieeeRadioPar_csmaRxWakeupMargin               182
#define _TYPE_ieeeRadioPar_csmaRxWakeupMargin                   uint16_t
#define _POSITION_ieeeRadioPar_ccaCorrWindow                    184
#define _TYPE_ieeeRadioPar_ccaCorrWindow                        uint16_t
#define _POSITION_ieeeRadioPar_rxCcaCorrValidTime               186
#define _TYPE_ieeeRadioPar_rxCcaCorrValidTime                   uint16_t
#define _LAST_POSITION_ieeeRadioPar                             186
#define _LAST_TYPE_ieeeRadioPar                                 uint16_t

#define _N_INIT_SETS_ieeeRadioPar 1
#define _N_INIT_WORDS_ieeeRadioPar 11
#define _START_INIT_WIDX_ieeeRadioPar 36
static uint32_t const __init_ieeeRadioPar[_N_INIT_SETS_ieeeRadioPar][_N_INIT_WORDS_ieeeRadioPar] = {
   {
      0x00007F08, 0xF39F0002, 0x3397FFFF, 0x338FFFFF, 0x338F338F, 0x0280338F, 0x050000E0, 0x00000200, 
      0x00000200, 0x00800680, 0x02400200
   }
};

#endif
